"""User entity for the loan service."""

from __future__ import annotations

from dataclasses import dataclass

from loans.domain.email import Email


class InvalidUserDataError(ValueError):
    """Raised when user account data violates loan service rules."""


@dataclass(slots=True)
class User:
    """A library member account: name plus the email that identifies it.

    The ``user_id`` is generated by the system; clients never provide it.
    """

    user_id: str
    name: str
    email: Email

    def __post_init__(self) -> None:
        if not self.user_id:
            raise InvalidUserDataError("user_id must not be empty")
        if not self.name:
            raise InvalidUserDataError("user name must not be empty")
