"""Borrow-book use case for the loan service."""

from __future__ import annotations

import uuid
from collections.abc import Callable
from dataclasses import dataclass
from datetime import date

from loans.domain.exceptions import UnknownUserError
from loans.domain.isbn import Isbn
from loans.domain.loan import InvalidLoanDataError, Loan
from loans.domain.ports import LoanRepository, UserRepository


def _default_loan_id() -> str:
    """Generate a system-unique loan id."""
    return uuid.uuid4().hex


@dataclass(frozen=True)
class BorrowBookCommand:
    """Input for the borrow-book use case.

    The loan id is generated by the system; the command carries none.
    """

    user_id: str = ""
    isbn: str = ""


class BorrowBook:
    """Registers a borrow request as a PENDING loan.

    The request is accepted as soon as the user exists and the isbn is in
    ISBN-13 format; reserving stock happens later, out of band. There is no
    limit on concurrent active loans per user.

    Raises ``InvalidLoanDataError`` for a missing user id,
    ``IsbnValidationError`` for a malformed isbn, and ``UnknownUserError``
    when the user id does not name an existing account.
    """

    def __init__(
        self,
        users: UserRepository,
        loans: LoanRepository,
        id_factory: Callable[[], str] = _default_loan_id,
        date_factory: Callable[[], date] = date.today,
    ) -> None:
        """Bind the use case to its ports and id/date generators."""
        self._users = users
        self._loans = loans
        self._id_factory = id_factory
        self._date_factory = date_factory

    async def execute(self, command: BorrowBookCommand) -> Loan:
        """Create and persist the PENDING loan described by the command."""
        if not command.user_id:
            raise InvalidLoanDataError("user_id must not be empty")
        isbn = Isbn(command.isbn)
        user = await self._users.get_by_id(command.user_id)
        if user is None:
            raise UnknownUserError(command.user_id)
        loan = Loan(
            loan_id=self._id_factory(),
            user_id=user.user_id,
            isbn=isbn,
            requested_on=self._date_factory(),
        )
        await self._loans.save(loan)
        return loan
